/*
 * Copyright (c) 2011, okazoh_tk. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *  - Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#define EGLAPI
#include <EGL/egl.h>
#include "EGLStrings.h"
#include "Utility.h"

const static Pair<EGLint> CR_EGL_STRINGS[] = {
    CR_REC(EGL_SUCCESS),
    CR_REC(EGL_NOT_INITIALIZED),
    CR_REC(EGL_BAD_ACCESS),
    CR_REC(EGL_BAD_ALLOC),
    CR_REC(EGL_BAD_ATTRIBUTE),
    CR_REC(EGL_BAD_CONFIG),
    CR_REC(EGL_BAD_CONTEXT),
    CR_REC(EGL_BAD_CURRENT_SURFACE),
    CR_REC(EGL_BAD_DISPLAY),
    CR_REC(EGL_BAD_MATCH),
    CR_REC(EGL_BAD_NATIVE_PIXMAP),
    CR_REC(EGL_BAD_NATIVE_WINDOW),
    CR_REC(EGL_BAD_PARAMETER),
    CR_REC(EGL_BAD_SURFACE),
    CR_REC(EGL_CONTEXT_LOST),
    CR_REC(EGL_BUFFER_SIZE),
    CR_REC(EGL_ALPHA_SIZE),
    CR_REC(EGL_BLUE_SIZE),
    CR_REC(EGL_GREEN_SIZE),
    CR_REC(EGL_RED_SIZE),
    CR_REC(EGL_DEPTH_SIZE),
    CR_REC(EGL_STENCIL_SIZE),
    CR_REC(EGL_CONFIG_CAVEAT),
    CR_REC(EGL_CONFIG_ID),
    CR_REC(EGL_LEVEL),
    CR_REC(EGL_MAX_PBUFFER_HEIGHT),
    CR_REC(EGL_MAX_PBUFFER_PIXELS),
    CR_REC(EGL_MAX_PBUFFER_WIDTH),
    CR_REC(EGL_NATIVE_RENDERABLE),
    CR_REC(EGL_NATIVE_VISUAL_ID),
    CR_REC(EGL_NATIVE_VISUAL_TYPE),
    CR_REC(EGL_SAMPLES),
    CR_REC(EGL_SAMPLE_BUFFERS),
    CR_REC(EGL_SURFACE_TYPE),
    CR_REC(EGL_TRANSPARENT_TYPE),
    CR_REC(EGL_TRANSPARENT_BLUE_VALUE),
    CR_REC(EGL_TRANSPARENT_GREEN_VALUE),
    CR_REC(EGL_TRANSPARENT_RED_VALUE),
    CR_REC(EGL_NONE),
    CR_REC(EGL_BIND_TO_TEXTURE_RGB),
    CR_REC(EGL_BIND_TO_TEXTURE_RGBA),
    CR_REC(EGL_MIN_SWAP_INTERVAL),
    CR_REC(EGL_MAX_SWAP_INTERVAL),
    CR_REC(EGL_LUMINANCE_SIZE),
    CR_REC(EGL_ALPHA_MASK_SIZE),
    CR_REC(EGL_COLOR_BUFFER_TYPE),
    CR_REC(EGL_RENDERABLE_TYPE),
    CR_REC(EGL_MATCH_NATIVE_PIXMAP),
    CR_REC(EGL_CONFORMANT),
    CR_REC(EGL_SLOW_CONFIG),
    CR_REC(EGL_NON_CONFORMANT_CONFIG),
    CR_REC(EGL_TRANSPARENT_RGB),
    CR_REC(EGL_RGB_BUFFER),
    CR_REC(EGL_LUMINANCE_BUFFER),
    CR_REC(EGL_NO_TEXTURE),
    CR_REC(EGL_TEXTURE_RGB),
    CR_REC(EGL_TEXTURE_RGBA),
    CR_REC(EGL_TEXTURE_2D),
    CR_REC(EGL_VENDOR),
    CR_REC(EGL_VERSION),
    CR_REC(EGL_EXTENSIONS),
    CR_REC(EGL_CLIENT_APIS),
    CR_REC(EGL_HEIGHT),
    CR_REC(EGL_WIDTH),
    CR_REC(EGL_LARGEST_PBUFFER),
    CR_REC(EGL_TEXTURE_FORMAT),
    CR_REC(EGL_TEXTURE_TARGET),
    CR_REC(EGL_MIPMAP_TEXTURE),
    CR_REC(EGL_MIPMAP_LEVEL),
    CR_REC(EGL_RENDER_BUFFER),
    CR_REC(EGL_VG_COLORSPACE),
    CR_REC(EGL_VG_ALPHA_FORMAT),
    CR_REC(EGL_HORIZONTAL_RESOLUTION),
    CR_REC(EGL_VERTICAL_RESOLUTION),
    CR_REC(EGL_PIXEL_ASPECT_RATIO),
    CR_REC(EGL_SWAP_BEHAVIOR),
    CR_REC(EGL_MULTISAMPLE_RESOLVE),
    CR_REC(EGL_BACK_BUFFER),
    CR_REC(EGL_SINGLE_BUFFER),
    CR_REC(EGL_VG_COLORSPACE_sRGB),
    CR_REC(EGL_VG_COLORSPACE_LINEAR),
    CR_REC(EGL_VG_ALPHA_FORMAT_NONPRE),
    CR_REC(EGL_VG_ALPHA_FORMAT_PRE),
    CR_REC(EGL_UNKNOWN),
    CR_REC(EGL_BUFFER_PRESERVED),
    CR_REC(EGL_BUFFER_DESTROYED),
    CR_REC(EGL_OPENVG_IMAGE),
    CR_REC(EGL_CONTEXT_CLIENT_TYPE),
    CR_REC(EGL_CONTEXT_CLIENT_VERSION),
    CR_REC(EGL_MULTISAMPLE_RESOLVE_DEFAULT),
    CR_REC(EGL_MULTISAMPLE_RESOLVE_BOX),
    CR_REC(EGL_OPENGL_ES_API),
    CR_REC(EGL_OPENVG_API),
    CR_REC(EGL_OPENGL_API),
    CR_REC(EGL_DRAW),
    CR_REC(EGL_READ),
    CR_REC(EGL_CORE_NATIVE_ENGINE),
};
